from __future__ import annotations

from typing import Any, Dict, Iterable, List, Tuple


def lesson(
    lesson_id: str,
    volume: str,
    unit_no: int,
    title: str,
    chars: str,
    unit_name: str,
    category: str = "课文",
) -> Dict[str, Any]:
    char_list = [char for char in chars if char.strip()]
    return {
        "id": lesson_id,
        "grade": "一年级",
        "volume": volume,
        "unit_no": unit_no,
        "unit_name": unit_name,
        "category": category,
        "title": title,
        "chars": char_list,
        "content": (
            f"部编版一年级{volume}《{title}》知识库条目："
            f"本课重点围绕“{'、'.join(char_list[:12])}”等生字词开展读准字音、"
            "认清字形、组词听写、形近字辨析和易错提醒。教师可继续上传教材截图"
            "或粘贴课文内容，生成更贴合班级进度的学习包。"
        ),
    }


# 目录依据人民教育出版社公开教材目录整理；仅保存目录、生字与教学元数据，
# 不内置教材完整课文正文，正式使用时以学校实际教材版本为准。
YEAR_ONE_LESSONS: List[Dict[str, Any]] = [
    lesson("pep_g1a_u1_01_tiandiren", "上册", 1, "天地人", "天地人你我他", "识字（一）", "识字"),
    lesson("pep_g1a_u1_02_jinmushuihuotu", "上册", 1, "金木水火土", "一二三四五上下", "识字（一）", "识字"),
    lesson("pep_g1a_u1_03_kouermu", "上册", 1, "口耳目", "口耳目手足站坐", "识字（一）", "识字"),
    lesson("pep_g1a_u1_04_riyueshuihuo", "上册", 1, "日月水火", "日月水火山石田禾", "识字（一）", "识字"),
    lesson("pep_g1a_u1_05_duiyunge", "上册", 1, "对韵歌", "对云雨风花鸟虫", "识字（一）", "识字"),
    lesson("pep_g1a_u4_01_qiutian", "上册", 4, "秋天", "秋气了树叶片大飞会个", "课文（一）"),
    lesson("pep_g1a_u4_02_xiaoxiaodechuan", "上册", 4, "小小的船", "的船两头在里看见闪星", "课文（一）"),
    lesson("pep_g1a_u4_03_jiangnan", "上册", 4, "江南", "江南可采莲鱼东西北", "课文（一）"),
    lesson("pep_g1a_u4_04_siji", "上册", 4, "四季", "尖说春青蛙夏弯地就冬", "课文（一）"),
    lesson("pep_g1a_u5_06_hua", "上册", 5, "画", "画远有色近听无声去还来", "识字（二）", "识字"),
    lesson("pep_g1a_u5_07_daxiaoduoshao", "上册", 5, "大小多少", "大小多少黄牛只猫边鸭苹桃杏", "识字（二）", "识字"),
    lesson("pep_g1a_u5_08_xiaoshubao", "上册", 5, "小书包", "书包尺作业本笔刀课早校", "识字（二）", "识字"),
    lesson("pep_g1a_u5_09_riyueming", "上册", 5, "日月明", "明力尘从众双木林森条心", "识字（二）", "识字"),
    lesson("pep_g1a_u5_10_shengguoqi", "上册", 5, "升国旗", "升国旗中红歌起么美丽立", "识字（二）", "识字"),
    lesson("pep_g1a_u6_05_yingzi", "上册", 6, "影子", "影前后黑狗左右它好朋友", "课文（二）"),
    lesson("pep_g1a_u6_06_biweiba", "上册", 6, "比尾巴", "比尾巴谁长短把伞兔最公", "课文（二）"),
    lesson("pep_g1a_u6_07_qingwaxieshi", "上册", 6, "青蛙写诗", "青蛙写诗点要过给当串们以成", "课文（二）"),
    lesson("pep_g1a_u6_08_yudianer", "上册", 6, "雨点儿", "雨点数彩半空问到方没更绿出长", "课文（二）"),
    lesson("pep_g1a_u7_09_mingtianyaoyuanzu", "上册", 7, "明天要远足", "明天睡那海真老师吗同什才亮", "课文（三）"),
    lesson("pep_g1a_u7_10_dahaishixiao", "上册", 7, "大还是小", "大小时侯觉得自己很穿衣服快", "课文（三）"),
    lesson("pep_g1a_u7_11_xianglian", "上册", 7, "项链", "蓝又笑着向和贝娃挂活金", "课文（三）"),
    lesson("pep_g1a_u8_12_xuedilidexiaohuajia", "上册", 8, "雪地里的小画家", "雪地里群竹牙用几步为参加洞着", "课文（四）"),
    lesson("pep_g1a_u8_13_wuyaheishui", "上册", 8, "乌鸦喝水", "乌鸦处找办旁许法放进高", "课文（四）"),
    lesson("pep_g1a_u8_14_xiaowoniu", "上册", 8, "小蜗牛", "小蜗牛住孩玩吧发芽爬呀久回全变", "课文（四）"),
    lesson("pep_g1b_u1_01_chunxiaqiu_dong", "下册", 1, "春夏秋冬", "春夏秋冬风雪花飞入", "识字（一）", "识字"),
    lesson("pep_g1b_u1_02_xingshige", "下册", 1, "姓氏歌", "姓什么双国王方", "识字（一）", "识字"),
    lesson("pep_g1b_u1_03_xiaoqingwa", "下册", 1, "小青蛙", "青清气晴情请生", "识字（一）", "识字"),
    lesson("pep_g1b_u1_04_caizimi", "下册", 1, "猜字谜", "字左右红时动万", "识字（一）", "识字"),
    lesson("pep_g1b_u2_01_chishuibuwangwajingren", "下册", 2, "吃水不忘挖井人", "吃叫主江住没以", "课文（一）"),
    lesson("pep_g1b_u2_02_woduoxiangqukankan", "下册", 2, "我多想去看看", "会走北京门广", "课文（一）"),
    lesson("pep_g1b_u2_03_yigejieyige", "下册", 2, "一个接一个", "过各种样伙伴这", "课文（一）"),
    lesson("pep_g1b_u2_04_sigetaiyang", "下册", 2, "四个太阳", "太阳校金秋因为", "课文（一）"),
    lesson("pep_g1b_u3_05_xiaogongjihexiaoyazi", "下册", 3, "小公鸡和小鸭子", "他地河说也听哥", "课文（二）"),
    lesson("pep_g1b_u3_06_shuhexique", "下册", 3, "树和喜鹊", "单居招呼快乐", "课文（二）"),
    lesson("pep_g1b_u3_07_zenmedoukuaile", "下册", 3, "怎么都快乐", "玩很当音讲行许", "课文（二）"),
    lesson("pep_g1b_u4_08_jingyesi", "下册", 4, "静夜思", "思床前光低故乡", "课文（三）"),
    lesson("pep_g1b_u4_09_yese", "下册", 4, "夜色", "色外看爸晚笑再", "课文（三）"),
    lesson("pep_g1b_u4_10_duanwuzong", "下册", 4, "端午粽", "午节叶米真分豆", "课文（三）"),
    lesson("pep_g1b_u4_11_caihong", "下册", 4, "彩虹", "那着到高兴千成", "课文（三）"),
    lesson("pep_g1b_u5_05_dongwuerge", "下册", 5, "动物儿歌", "间迷造运池欢网", "识字（二）", "识字"),
    lesson("pep_g1b_u5_06_guduijin", "下册", 5, "古对今", "古凉细夕李语香", "识字（二）", "识字"),
    lesson("pep_g1b_u5_07_caochangshang", "下册", 5, "操场上", "打拍跑足声身体", "识字（二）", "识字"),
    lesson("pep_g1b_u5_08_renzhichu", "下册", 5, "人之初", "之相近习远玉义", "识字（二）", "识字"),
    lesson("pep_g1b_u6_12_gushiershou", "下册", 6, "古诗二首", "首采无树爱尖角", "课文（四）"),
    lesson("pep_g1b_u6_13_heyeyuanyuan", "下册", 6, "荷叶圆圆", "亮机台放鱼朵美", "课文（四）"),
    lesson("pep_g1b_u6_14_yaoxiayule", "下册", 6, "要下雨了", "要过这呀边吗吧加", "课文（四）"),
    lesson("pep_g1b_u7_15_wenjudijia", "下册", 7, "文具的家", "文具平办让包伙伴", "课文（五）"),
    lesson("pep_g1b_u7_16_yifenzhong", "下册", 7, "一分钟", "钟丁元面车共坐", "课文（五）"),
    lesson("pep_g1b_u7_17_dongwuwangguokaidahui", "下册", 7, "动物王国开大会", "要连百还舌点", "课文（五）"),
    lesson("pep_g1b_u7_18_xiaohouzixiashan", "下册", 7, "小猴子下山", "块非常往瓜进空", "课文（五）"),
    lesson("pep_g1b_u8_19_mianhuaguniang", "下册", 8, "棉花姑娘", "病医别干奇七星", "课文（六）"),
    lesson("pep_g1b_u8_20_gudong", "下册", 8, "咕咚", "吓怕跟家羊象都", "课文（六）"),
    lesson("pep_g1b_u8_21_xiaobihujieweiba", "下册", 8, "小壁虎借尾巴", "捉条爬姐您好草房", "课文（六）"),
]


PINYIN_TONE3: Dict[str, str] = {
    "一": "yi1",
    "二": "er4",
    "三": "san1",
    "四": "si4",
    "五": "wu3",
    "上": "shang4",
    "下": "xia4",
    "天": "tian1",
    "地": "di4",
    "人": "ren2",
    "你": "ni3",
    "我": "wo3",
    "他": "ta1",
    "口": "kou3",
    "耳": "er3",
    "目": "mu4",
    "手": "shou3",
    "足": "zu2",
    "站": "zhan4",
    "坐": "zuo4",
    "日": "ri4",
    "月": "yue4",
    "水": "shui3",
    "火": "huo3",
    "山": "shan1",
    "石": "shi2",
    "田": "tian2",
    "禾": "he2",
    "对": "dui4",
    "云": "yun2",
    "雨": "yu3",
    "风": "feng1",
    "花": "hua1",
    "鸟": "niao3",
    "虫": "chong2",
    "秋": "qiu1",
    "气": "qi4",
    "了": "le",
    "树": "shu4",
    "叶": "ye4",
    "片": "pian4",
    "大": "da4",
    "小": "xiao3",
    "飞": "fei1",
    "会": "hui4",
    "个": "ge4",
    "的": "de",
    "船": "chuan2",
    "两": "liang3",
    "头": "tou2",
    "在": "zai4",
    "里": "li3",
    "看": "kan4",
    "见": "jian4",
    "闪": "shan3",
    "星": "xing1",
    "江": "jiang1",
    "南": "nan2",
    "可": "ke3",
    "采": "cai3",
    "莲": "lian2",
    "鱼": "yu2",
    "东": "dong1",
    "西": "xi1",
    "北": "bei3",
    "尖": "jian1",
    "说": "shuo1",
    "春": "chun1",
    "青": "qing1",
    "蛙": "wa1",
    "夏": "xia4",
    "弯": "wan1",
    "就": "jiu4",
    "冬": "dong1",
    "画": "hua4",
    "远": "yuan3",
    "有": "you3",
    "色": "se4",
    "近": "jin4",
    "听": "ting1",
    "无": "wu2",
    "声": "sheng1",
    "去": "qu4",
    "还": "hai2",
    "来": "lai2",
    "多": "duo1",
    "少": "shao3",
    "黄": "huang2",
    "牛": "niu2",
    "只": "zhi1",
    "猫": "mao1",
    "边": "bian1",
    "鸭": "ya1",
    "苹": "ping2",
    "桃": "tao2",
    "杏": "xing4",
    "书": "shu1",
    "包": "bao1",
    "尺": "chi3",
    "作": "zuo4",
    "业": "ye4",
    "本": "ben3",
    "笔": "bi3",
    "刀": "dao1",
    "课": "ke4",
    "早": "zao3",
    "校": "xiao4",
    "明": "ming2",
    "力": "li4",
    "尘": "chen2",
    "从": "cong2",
    "众": "zhong4",
    "双": "shuang1",
    "木": "mu4",
    "林": "lin2",
    "森": "sen1",
    "条": "tiao2",
    "心": "xin1",
    "升": "sheng1",
    "国": "guo2",
    "旗": "qi2",
    "中": "zhong1",
    "红": "hong2",
    "歌": "ge1",
    "起": "qi3",
    "么": "me",
    "美": "mei3",
    "丽": "li4",
    "立": "li4",
    "影": "ying3",
    "前": "qian2",
    "后": "hou4",
    "黑": "hei1",
    "狗": "gou3",
    "左": "zuo3",
    "右": "you4",
    "它": "ta1",
    "好": "hao3",
    "朋": "peng2",
    "友": "you3",
    "比": "bi3",
    "尾": "wei3",
    "巴": "ba",
    "谁": "shui2",
    "长": "chang2",
    "短": "duan3",
    "把": "ba3",
    "伞": "san3",
    "兔": "tu4",
    "最": "zui4",
    "公": "gong1",
    "写": "xie3",
    "诗": "shi1",
    "点": "dian3",
    "要": "yao4",
    "过": "guo4",
    "给": "gei3",
    "当": "dang1",
    "串": "chuan4",
    "们": "men",
    "以": "yi3",
    "成": "cheng2",
    "数": "shu4",
    "彩": "cai3",
    "半": "ban4",
    "空": "kong1",
    "问": "wen4",
    "到": "dao4",
    "方": "fang1",
    "没": "mei2",
    "更": "geng4",
    "绿": "lv4",
    "出": "chu1",
    "睡": "shui4",
    "那": "na4",
    "海": "hai3",
    "真": "zhen1",
    "老": "lao3",
    "师": "shi1",
    "吗": "ma",
    "同": "tong2",
    "什": "shen2",
    "才": "cai2",
    "亮": "liang4",
    "时": "shi2",
    "侯": "hou2",
    "候": "hou4",
    "觉": "jue2",
    "得": "de",
    "自": "zi4",
    "己": "ji3",
    "很": "hen3",
    "穿": "chuan1",
    "衣": "yi1",
    "服": "fu2",
    "快": "kuai4",
    "蓝": "lan2",
    "又": "you4",
    "笑": "xiao4",
    "着": "zhe",
    "向": "xiang4",
    "和": "he2",
    "贝": "bei4",
    "娃": "wa2",
    "挂": "gua4",
    "活": "huo2",
    "金": "jin1",
    "群": "qun2",
    "竹": "zhu2",
    "牙": "ya2",
    "用": "yong4",
    "几": "ji3",
    "步": "bu4",
    "为": "wei4",
    "参": "can1",
    "加": "jia1",
    "洞": "dong4",
    "乌": "wu1",
    "鸦": "ya1",
    "处": "chu4",
    "找": "zhao3",
    "办": "ban4",
    "旁": "pang2",
    "许": "xu3",
    "法": "fa3",
    "放": "fang4",
    "进": "jin4",
    "高": "gao1",
    "住": "zhu4",
    "孩": "hai2",
    "玩": "wan2",
    "蜗": "wo1",
    "吧": "ba",
    "发": "fa1",
    "芽": "ya2",
    "爬": "pa2",
    "呀": "ya",
    "久": "jiu3",
    "回": "hui2",
    "全": "quan2",
    "变": "bian4",
    "雪": "xue3",
    "入": "ru4",
    "姓": "xing4",
    "双": "shuang1",
    "王": "wang2",
    "清": "qing1",
    "晴": "qing2",
    "情": "qing2",
    "请": "qing3",
    "生": "sheng1",
    "字": "zi4",
    "动": "dong4",
    "万": "wan4",
    "吃": "chi1",
    "叫": "jiao4",
    "主": "zhu3",
    "走": "zou3",
    "京": "jing1",
    "门": "men2",
    "广": "guang3",
    "各": "ge4",
    "种": "zhong3",
    "样": "yang4",
    "伙": "huo3",
    "伴": "ban4",
    "这": "zhe4",
    "太": "tai4",
    "阳": "yang2",
    "因": "yin1",
    "河": "he2",
    "也": "ye3",
    "哥": "ge1",
    "单": "dan1",
    "居": "ju1",
    "招": "zhao1",
    "呼": "hu1",
    "乐": "le4",
    "音": "yin1",
    "讲": "jiang3",
    "行": "xing2",
    "静": "jing4",
    "思": "si1",
    "床": "chuang2",
    "光": "guang1",
    "低": "di1",
    "故": "gu4",
    "乡": "xiang1",
    "外": "wai4",
    "爸": "ba4",
    "晚": "wan3",
    "再": "zai4",
    "午": "wu3",
    "节": "jie2",
    "米": "mi3",
    "分": "fen1",
    "豆": "dou4",
    "虹": "hong2",
    "兴": "xing4",
    "千": "qian1",
    "间": "jian1",
    "迷": "mi2",
    "造": "zao4",
    "运": "yun4",
    "池": "chi2",
    "欢": "huan1",
    "网": "wang3",
    "古": "gu3",
    "凉": "liang2",
    "细": "xi4",
    "夕": "xi1",
    "李": "li3",
    "语": "yu3",
    "香": "xiang1",
    "打": "da3",
    "拍": "pai1",
    "跑": "pao3",
    "身": "shen1",
    "体": "ti3",
    "之": "zhi1",
    "相": "xiang1",
    "习": "xi2",
    "玉": "yu4",
    "义": "yi4",
    "首": "shou3",
    "爱": "ai4",
    "角": "jiao3",
    "荷": "he2",
    "圆": "yuan2",
    "机": "ji1",
    "台": "tai2",
    "朵": "duo3",
    "文": "wen2",
    "具": "ju4",
    "平": "ping2",
    "让": "rang4",
    "钟": "zhong1",
    "丁": "ding1",
    "元": "yuan2",
    "面": "mian4",
    "车": "che1",
    "共": "gong4",
    "连": "lian2",
    "百": "bai3",
    "舌": "she2",
    "块": "kuai4",
    "非": "fei1",
    "常": "chang2",
    "往": "wang3",
    "瓜": "gua1",
    "病": "bing4",
    "医": "yi1",
    "别": "bie2",
    "干": "gan4",
    "奇": "qi2",
    "七": "qi1",
    "吓": "xia4",
    "怕": "pa4",
    "跟": "gen1",
    "家": "jia1",
    "羊": "yang2",
    "象": "xiang4",
    "都": "dou1",
    "捉": "zhuo1",
    "姐": "jie3",
    "您": "nin2",
    "草": "cao3",
    "房": "fang2",
}


WORD_OVERRIDES: Dict[str, List[str]] = {
    "春": ["春天", "春风"],
    "夏": ["夏天", "夏日"],
    "秋": ["秋天", "秋风"],
    "冬": ["冬天", "冬雪"],
    "天": ["天空", "今天"],
    "地": ["土地", "大地"],
    "人": ["人民", "大人"],
    "你": ["你好", "你们"],
    "我": ["我们", "我的"],
    "他": ["他们", "他的"],
    "水": ["清水", "水果"],
    "火": ["火山", "火苗"],
    "山": ["大山", "山水"],
    "日": ["日月", "生日"],
    "月": ["月亮", "日月"],
    "风": ["大风", "春风"],
    "雨": ["下雨", "雨点"],
    "花": ["花朵", "开花"],
    "鸟": ["小鸟", "飞鸟"],
    "虫": ["小虫", "虫子"],
    "青": ["青草", "青蛙"],
    "清": ["清水", "清早"],
    "晴": ["晴天", "晴朗"],
    "情": ["心情", "友情"],
    "请": ["请问", "请坐"],
    "生": ["学生", "生日"],
    "字": ["生字", "写字"],
    "左": ["左边", "左右"],
    "右": ["右边", "左右"],
    "红": ["红色", "红花"],
    "动": ["动物", "活动"],
    "吃": ["吃水", "吃饭"],
    "叫": ["叫声", "叫好"],
    "主": ["主人", "主意"],
    "江": ["江水", "长江"],
    "住": ["住处", "住下"],
    "会": ["开会", "学会"],
    "走": ["走路", "走开"],
    "北": ["北京", "北方"],
    "京": ["北京", "京城"],
    "门": ["大门", "门口"],
    "广": ["广大", "广场"],
    "太": ["太阳", "太大"],
    "阳": ["太阳", "阳光"],
    "金": ["金色", "金子"],
    "树": ["树木", "大树"],
    "快": ["快乐", "飞快"],
    "乐": ["快乐", "欢乐"],
    "静": ["安静", "静夜"],
    "思": ["思念", "心思"],
    "光": ["月光", "阳光"],
    "色": ["颜色", "夜色"],
    "午": ["中午", "午后"],
    "节": ["节日", "端午节"],
    "叶": ["叶子", "荷叶"],
    "米": ["大米", "米饭"],
    "真": ["认真", "真好"],
    "分": ["分开", "十分"],
    "豆": ["豆子", "红豆"],
    "彩": ["彩虹", "彩色"],
    "虹": ["彩虹", "虹桥"],
    "高": ["高兴", "高山"],
    "兴": ["高兴", "兴奋"],
    "间": ["中间", "房间"],
    "迷": ["迷路", "入迷"],
    "造": ["造句", "制造"],
    "运": ["运动", "运气"],
    "池": ["水池", "池塘"],
    "欢": ["欢乐", "喜欢"],
    "网": ["上网", "网子"],
    "古": ["古人", "古诗"],
    "凉": ["凉风", "清凉"],
    "细": ["细心", "细小"],
    "语": ["语文", "语言"],
    "香": ["花香", "清香"],
    "打": ["打字", "打球"],
    "拍": ["拍手", "拍打"],
    "跑": ["跑步", "长跑"],
    "足": ["足球", "手足"],
    "声": ["声音", "笑声"],
    "身": ["身体", "身边"],
    "体": ["身体", "字体"],
    "文": ["语文", "文字"],
    "具": ["文具", "工具"],
    "家": ["大家", "回家"],
}


RADICAL_OVERRIDES: Dict[str, str] = {
    "清": "氵",
    "河": "氵",
    "江": "氵",
    "池": "氵",
    "晴": "日",
    "时": "日",
    "明": "日",
    "晚": "日",
    "情": "忄",
    "快": "忄",
    "怕": "忄",
    "请": "讠",
    "说": "讠",
    "语": "讠",
    "讲": "讠",
    "让": "讠",
    "们": "亻",
    "你": "亻",
    "他": "亻",
    "住": "亻",
    "什": "亻",
    "伙": "亻",
    "伴": "亻",
    "体": "亻",
    "林": "木",
    "森": "木",
    "树": "木",
    "校": "木",
    "机": "木",
    "妈": "女",
    "姐": "女",
    "娃": "女",
    "姓": "女",
    "草": "艹",
    "花": "艹",
    "荷": "艹",
    "莲": "艹",
    "苹": "艹",
    "蓝": "艹",
    "红": "纟",
    "绿": "纟",
    "给": "纟",
    "间": "门",
    "问": "门",
    "闪": "门",
    "国": "囗",
    "园": "囗",
    "圆": "囗",
    "听": "口",
    "吃": "口",
    "叫": "口",
    "吗": "口",
    "吧": "口",
    "呀": "口",
    "呼": "口",
    "叶": "口",
    "古": "口",
    "鸟": "鸟",
    "鸭": "鸟",
    "鸦": "鸟",
    "鹅": "鸟",
    "狗": "犭",
    "猫": "犭",
    "猴": "犭",
    "猪": "犭",
    "打": "扌",
    "拍": "扌",
    "找": "扌",
    "捉": "扌",
    "挂": "扌",
    "放": "攵",
    "跑": "足",
    "跟": "足",
    "跳": "足",
    "船": "舟",
    "笔": "竹",
    "笑": "竹",
    "答": "竹",
    "空": "穴",
    "穿": "穴",
    "雪": "雨",
    "雷": "雨",
    "露": "雨",
    "房": "户",
    "床": "广",
    "广": "广",
    "这": "辶",
    "过": "辶",
    "进": "辶",
    "远": "辶",
    "近": "辶",
    "连": "辶",
    "迷": "辶",
    "运": "辶",
}


INDEPENDENT_CHARS = set("一二三四五上下天地人口耳目手足日月水火山石田禾云雨风虫木林森心力刀尺本中立大大小少金牛车门王玉米贝牙又几己")
LEFT_RIGHT_RADICALS = {"氵", "日", "忄", "讠", "亻", "木", "女", "纟", "口", "鸟", "犭", "扌", "足"}


def display_pinyin(tone3: str) -> str:
    if not tone3:
        return ""
    tone = tone3[-1]
    syllable = tone3[:-1] if tone.isdigit() else tone3
    syllable = syllable.replace("v", "ü")
    if tone not in "1234":
        return syllable
    vowels = ["a", "o", "e", "i", "u", "ü"]
    marked = {
        "a": "āáǎà",
        "o": "ōóǒò",
        "e": "ēéěè",
        "i": "īíǐì",
        "u": "ūúǔù",
        "ü": "ǖǘǚǜ",
    }
    target = ""
    for candidate in ("a", "o", "e"):
        if candidate in syllable:
            target = candidate
            break
    if not target and "iu" in syllable:
        target = "u"
    if not target and "ui" in syllable:
        target = "i"
    if not target:
        target = next((vowel for vowel in vowels if vowel in syllable), "")
    if not target:
        return syllable
    return syllable.replace(target, marked[target][int(tone) - 1], 1)


def all_lesson_chars() -> List[str]:
    chars: List[str] = []
    for item in YEAR_ONE_LESSONS:
        for char in item["chars"]:
            if char not in chars:
                chars.append(char)
    return chars


def words_for(char: str) -> List[str]:
    if char in WORD_OVERRIDES:
        return WORD_OVERRIDES[char]
    return [f"{char}字", f"{char}词"]


def structure_for(char: str, radical: str) -> str:
    if char in INDEPENDENT_CHARS:
        return "独体字"
    if radical in LEFT_RIGHT_RADICALS:
        return "左右结构"
    if radical in {"艹", "竹", "雨", "穴"}:
        return "上下结构"
    if radical in {"辶", "广", "户"}:
        return "半包围结构"
    return "待教师确认"


def build_textbook_char_meta(chars: Iterable[str]) -> Dict[str, Dict[str, Any]]:
    result: Dict[str, Dict[str, Any]] = {}
    for char in chars:
        tone3 = PINYIN_TONE3.get(char, "")
        radical = RADICAL_OVERRIDES.get(char, char if char in INDEPENDENT_CHARS else "待教师确认")
        words = words_for(char)
        needs_review = radical == "待教师确认" or not tone3
        result[char] = {
            "pinyin": tone3,
            "display_pinyin": display_pinyin(tone3),
            "radical": radical,
            "structure": structure_for(char, radical),
            "stroke_count": None,
            "stroke_order": [],
            "words": words,
            "simple_sentence": f"我会读写“{words[0]}”。",
            "confusing_chars": [],
            "common_mistakes": ["注意看清偏旁、关键笔画和字在田字格中的位置。"],
            "needs_teacher_review": needs_review,
        }
    return result


TEXTBOOK_CHAR_META = build_textbook_char_meta(all_lesson_chars())


def source_summary() -> Tuple[int, int]:
    return len(YEAR_ONE_LESSONS), len(TEXTBOOK_CHAR_META)
